import React from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useRiverGuard } from '../context/RiverGuardContext';
import Icon from '../components/common/Icon';
import Badge from '../components/common/Badge';
import Button from '../components/common/Button';

export const ReportPreview = () => {
  const { reportId } = useParams();
  const navigate = useNavigate();
  const { reports } = useRiverGuard();

  const report = reports.find(r => r.id === reportId) || reports[0];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Action Bar (Hidden on print) */}
      <div className="print:hidden flex items-center justify-between pb-3 border-b border-outline-variant/20">
        <Link
          to="/reports"
          className="font-label-code text-label-code-sm text-secondary hover:text-primary flex items-center gap-1 font-medium hover:underline"
        >
          <Icon name="arrow_back" size={16} /> Back to Dossier Archive
        </Link>

        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            icon="print"
            onClick={handlePrint}
          >
            Print / Save to PDF
          </Button>
          <Button
            variant="primary"
            icon="compare"
            onClick={() => navigate(`/detection/${report.siteId}`)}
          >
            Open Live AI Analysis
          </Button>
        </div>
      </div>

      {/* Printable Formal Evidentiary Report Paper */}
      <div className="bg-white text-black p-8 md:p-12 rounded-xl shadow-md border border-outline-variant/40 print:shadow-none print:border-none print:p-0">
        {/* Government Header */}
        <div className="border-b-2 border-black pb-4 mb-6 flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-black text-white rounded-lg flex items-center justify-center font-bold text-xl">
              RG
            </div>
            <div>
              <h1 className="font-headline font-bold text-xl uppercase tracking-wider text-black">
                State Department of Water Resources & Mines
              </h1>
              <p className="font-label-code text-xs uppercase tracking-wide text-neutral-600">
                Fluvial Geomorphological Surveillance Wing · RiverGuard AI System
              </p>
            </div>
          </div>
          <div className="text-right font-label-code text-xs">
            <p className="font-bold">DOSSIER REF: {report.id}</p>
            <p className="text-neutral-600">DATE OF FILING: {report.date}</p>
            <p className="text-neutral-600">CLASSIFICATION: STATUTORY ADVISORY</p>
          </div>
        </div>

        {/* Title */}
        <div className="mb-6">
          <h2 className="font-headline font-bold text-xl text-black">
            {report.title}
          </h2>
          <div className="mt-2 flex items-center gap-4 text-xs font-label-code text-neutral-700">
            <span>Location: <strong>{report.siteName}</strong></span>
            <span>·</span>
            <span>Basin: <strong>{report.river}</strong></span>
            <span>·</span>
            <span>District: <strong>{report.district}</strong></span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="p-4 bg-neutral-100 rounded-lg mb-6 border-l-4 border-black">
          <h3 className="font-bold text-xs uppercase tracking-wider font-label-code mb-1">
            Preliminary Forensic Summary (Decision-Support Notice)
          </h3>
          <p className="text-sm leading-relaxed text-neutral-800">
            {report.summary}
          </p>
          <p className="text-xs italic text-neutral-500 mt-2">
            Notice: All metrics generated by multi-spectral satellite inference represent change indicators requiring ground-truthing verification prior to judicial determination.
          </p>
        </div>

        {/* Telemetry Metrics Table */}
        <div className="mb-6">
          <h3 className="font-bold text-xs uppercase tracking-wider font-label-code mb-2 text-neutral-700">
            Automated Sensor Inversion Parameters
          </h3>
          <table className="w-full text-left text-xs border border-neutral-300 font-label-code">
            <tbody>
              <tr className="border-b border-neutral-300">
                <td className="p-2.5 bg-neutral-100 font-semibold w-1/3">Disturbed Riverbed Surface Area</td>
                <td className="p-2.5">{report.affectedAreaM2?.toLocaleString()} square meters (approx {(report.affectedAreaM2 / 4047).toFixed(1)} acres)</td>
              </tr>
              <tr className="border-b border-neutral-300">
                <td className="p-2.5 bg-neutral-100 font-semibold">Estimated Volumetric Deficit</td>
                <td className="p-2.5 font-bold text-red-700">{report.estimatedVolumeM3?.toLocaleString()} cubic meters (estimated)</td>
              </tr>
              <tr className="border-b border-neutral-300">
                <td className="p-2.5 bg-neutral-100 font-semibold">Sensor Payload Architecture</td>
                <td className="p-2.5">{report.detectionType}</td>
              </tr>
              <tr className="border-b border-neutral-300">
                <td className="p-2.5 bg-neutral-100 font-semibold">Assigned Investigating Officer</td>
                <td className="p-2.5">{report.leadInvestigator} (GIS Enforcement Lead)</td>
              </tr>
              <tr>
                <td className="p-2.5 bg-neutral-100 font-semibold">Reference Cost Range</td>
                <td className="p-2.5">₹45–65 lakh (Illustrative Reference Only — Not a Legal or Financial Determination)</td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Action Directives */}
        <div className="mb-8">
          <h3 className="font-bold text-xs uppercase tracking-wider font-label-code mb-2 text-neutral-700">
            Recommended Action Directives for Field Taskforce
          </h3>
          <ul className="space-y-2 text-sm text-neutral-800 list-disc pl-5">
            {report.recommendations?.map((rec, i) => (
              <li key={i}>{rec}</li>
            ))}
          </ul>
        </div>

        {/* Verification Sign-Off Section */}
        <div className="pt-6 border-t-2 border-neutral-300 grid grid-cols-2 gap-8 text-xs font-label-code">
          <div>
            <p className="text-neutral-500 uppercase">Compiled By (AI Telemetry System):</p>
            <p className="font-bold text-sm mt-1">{report.leadInvestigator}</p>
            <p className="text-neutral-600">GIS Enforcement Lead, Water Resources</p>
            <div className="mt-4 pt-4 border-t border-neutral-400 w-48 text-neutral-400">
              Electronic Signature Certified
            </div>
          </div>

          <div>
            <p className="text-neutral-500 uppercase">Endorsing Executive Authority:</p>
            <p className="font-bold text-sm mt-1">District Magistrate Collectorate</p>
            <p className="text-neutral-600">Jurisdictional Revenue Division</p>
            <div className="mt-4 pt-4 border-t border-neutral-400 w-48 text-neutral-400">
              Seal & Verification Signature
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPreview;
